### PR TITLE
Fix crash on empty depot list (#729)

### LINKED ISSUE #729: [Bug]: Crash when trying to install Skautfold: Shrouded in Sanity (App 444590)
### Describe the bug

The app crashes immediately when I try to install [Skautfold: Shrouded in Sanity](https://store.steampowered.com/app/444590/Skautfold_Shrouded_in_Sanity/). 

It throws a `NoSuchElementException: Collection is empty.` when opening the manager dialog. According to the logcat, it says `There are 0 depots belonging to STEAM_444590` right before crashing, so it looks like the app is calling `.first()` on an empty depot list.

### Steps to reproduce

1. Open the app and go to the library.
2. Select Skautfold: Shrouded in Sanity.
3. Try to install the game / open the game manager dialog.
4. The app hard crashes.

### Expected behavior

It should either open the installation dialog normally, or show a graceful error/toast saying that there are no depots available, instead of completely crashing the app.

### GameNativeVersion

0.8.0

### Device Model

AYN Thor

### Android Version

13

### Additional Information

[pluvia_crash_2026-03-05_19-20-40.txt](https://github.com/user-attachments/files/25782972/pluvia_crash_2026-03-05_19-20-40.txt)

### New Issue

- [x] I have searched and did not find a similar issue to mine already listed.

### PR DESCRIPTION
**Pull request by jeremybernstein**
Fixes #729

## Summary
- `GameManagerDialog` calls `.first()` on depot list without checking empty, crashes with `NoSuchElementException` when a game returns 0 downloadable depots
- Fix: use `.firstOrNull()` and bail out of the `LaunchedEffect` if no depots

## Test plan
- [ ] Trigger a download when Steam returns 0 depots, verify no crash
- [ ] Verify normal games with depots still download correctly

---
## Summary by cubic
Prevent a crash in GameManagerDialog when a game has no downloadable depots or lacks a base depot. Use firstOrNull to pick the base depot (dlcAppId == INVALID_APP_ID) and return early in LaunchedEffect, so empty/missing depots don’t crash and normal downloads still work.

<sup>Written for commit 4c1a567d19bdb727c2aebc8db63cc4ff2f2a6201. Summary will update on new commits.</sup>

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed a crash in the game manager dialog when no base game depot is available. The dialog now safely checks for an eligible base depot, skips insertion if none exists, and—when present—ensures the base game is placed at the start of the downloadable apps list to preserve expected ordering and stability.

### CODE REVIEW

**Comment by jeremybernstein** [comment]
> **Explicit base depot filtering**: The current logic assumes the first sorted depot is the base game, but `DepotInfo` identifies base depots via `dlcAppId == INVALID_APP_ID`. Consider filtering explicitly:

This is additional to the crash fix, the original code did this, too. HOWEVER, because you're so charming, I've just pushed a fix for that. @coderabbitai

File: app/src/main/java/app/gamenative/ui/component/dialog/GameManagerDialog.kt [hunk 1]
```diff
@@ -141,7 +141,8 @@ fun GameManagerDialog(
         allDownloadableApps.sortBy { it.first }
 
         // Add Base Game
-        allDownloadableApps.add(0, Pair(gameId, downloadableDepots.toSortedMap().values.first()))
+        val baseDepot = downloadableDepots.values.firstOrNull { it.dlcAppId == INVALID_APP_ID } ?: return@LaunchedEffect
+        allDownloadableApps.add(0, Pair(gameId, baseDepot))
```
Comment (phobos665) [inline app/src/main/java/app/gamenative/ui/component/dialog/GameManagerDialog.kt:145]: How's the end-behaviour here? Will it just give an error toast?

Comment (jeremybernstein) [reply app/src/main/java/app/gamenative/ui/component/dialog/GameManagerDialog.kt:145]: it'll show a mostly-empty game summary page with a disabled "Install" button. We could probably improve that, but it's better than the crash. 0 depots appears to only happen when Valve's servers are misbehaving FWIW, so this is mostly coverage for a rare case.
