### PR TITLE
fix: serve cached images when device has no internet

### LINKED ISSUE #634: Serve cached images when device has no internet
Coil's default behavior always tries the network first, even when the device is offline. This causes image loads to fail (or hang until timeout) instead of serving the already-cached copy from disk.

### PR DESCRIPTION
**Pull request by jeremybernstein**
Closes #634

- Register a `ConnectivityManager.NetworkCallback` that tracks validated networks (filtering out VPN/mesh transports which don't reliably indicate internet)
- Add a Coil `Interceptor` that sets `networkCachePolicy(DISABLED)` when offline, forcing Coil to serve from disk cache without attempting network requests

---
## Summary by cubic
Serve cached images when the device has no internet by detecting validated connectivity and skipping Coil network requests. This prevents broken thumbnails and network errors while offline.

- **Bug Fixes**
  - Track validated internet via ConnectivityManager.NetworkCallback (ignores VPN/Wi‑Fi Aware/LoWPAN).
  - Add a Coil interceptor that disables network access when offline, serving images from disk cache.
  - Register/unregister the network callback in the activity lifecycle.

<sup>Written for commit a92ae2045a4f39d16aed2f0fc593bff1e8b7866f. Summary will update on new commits.</sup>

## Summary by CodeRabbit

* **New Features**
  * Improved offline support: image loading now adapts to connectivity and serves cached images when offline.
  * Smarter connectivity detection to more reliably determine internet availability and adjust app behavior.
* **Bug Fixes**
  * Reduced unnecessary network usage when internet is unavailable, improving load reliability and responsiveness.

### CODE REVIEW

File: app/src/main/java/app/gamenative/MainActivity.kt [hunk 1]
```diff
@@ -48,15 +49,49 @@ import com.winlator.core.AppUtils
...
+                validated.remove(network)
+            }
+            hasInternet.set(validated.isNotEmpty())
+        }
+
+        override fun onLost(network: Network) {
+            validated.remove(network)
+            hasInternet.set(validated.isNotEmpty())
+        }
+    }
```
[the remark this answers is not in the document]
Comment (jeremybernstein) [reply app/src/main/java/app/gamenative/MainActivity.kt:89]: I tried this in local testing, the problem is that, when initialized to `true`, if there is an already inactive internet state, we'll never get a change notification to disable it. This strategy works as expected, and, if active, internet is enabled before any image loading is attempted. @coderabbitai

**Comment by jeremybernstein** [comment]
This is most visible in Hero mode for games which use a header fallback (recent accepted PR), where the timeout is very long before failing to the cache.

File: app/src/main/java/app/gamenative/MainActivity.kt [hunk 2]
```diff
@@ -184,10 +229,20 @@ class MainActivity : ComponentActivity() {
...
+                        add(Interceptor { chain ->
+                            val request = if (!hasInternet) {
+                                chain.request.newBuilder()
+                                    .networkCachePolicy(CachePolicy.DISABLED)
+                                    .build()
+                            } else {
+                                chain.request
+                            }
+                            chain.proceed(request)
+                        })
```
Comment (utkarshdalal) [inline app/src/main/java/app/gamenative/MainActivity.kt:242]: is there a benefit to doing this vs always just using cached images? I feel like if we can we should use the cached ones.

File: app/src/main/java/app/gamenative/MainActivity.kt [hunk 3]
```diff
@@ -48,15 +49,50 @@ import com.winlator.core.AppUtils
...
+                validated.remove(network)
+            }
+            _hasInternet.set(validated.isNotEmpty())
+        }
+
+        override fun onLost(network: Network) {
+            validated.remove(network)
+            _hasInternet.set(validated.isNotEmpty())
+        }
+    }
```
Comment (utkarshdalal) [inline app/src/main/java/app/gamenative/MainActivity.kt:89]: I believe we already do something similar in LibraryAppScreen when checking for internet. Could we use this code to check for internet there too instead of duplicating?

File: app/src/main/java/app/gamenative/MainActivity.kt (hunk 2 above)
Comment (jeremybernstein) [reply app/src/main/java/app/gamenative/MainActivity.kt:242]: I guess there's the matter of images being updated at the server and missing those updates. In any case, it's a chicken-egg problem -- we don't find out whether we have the cached image until the connection fails.

File: app/src/main/java/app/gamenative/MainActivity.kt (hunk 3 above)
Comment (jeremybernstein) [reply app/src/main/java/app/gamenative/MainActivity.kt:89]: I can refactor (in another PR), no problem.
